version: 0.2

phases:
  build:
    commands:
      - tar -zcf SOURCES/alexchesters-utils.tar.gz src
      - rpmbuild --define "_topdir `pwd`" --define "debug_package %{nil}" -ba SPECS/utils.spec
      - ls -alh SRPMS
      - ls -alh RPMS/aarch64
      # - aws s3 cp RPMS/
