version: 0.2

env:
  parameter-store:
    "GITHUB_TOKEN": "/CodeBuild/GitHub-Token"

phases:
  build:
    commands:
      - tar -zcf SOURCES/alexchesters-utils.tar.gz src
      - rpmbuild --define "_topdir `pwd`" --define "debug_package %{nil}" -ba SPECS/utils.spec
      - aws s3 cp RPMS/x86_64 s3://$BUILDS_BUCKET/ --recursive
  post_build:
    commands:
      - ./ci/scripts/bump $GITHUB_TOKEN
