Parameters:
  Environment:
    Description: The infrastructure environment
    Type: String
    AllowedValues:
      - live
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Environment}-alexchesters-utils"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - "s3:GetObject"
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${Bucket}/*"
            Condition:
              StringEquals:
                aws:PrincipalOrgID: o-hru7a3vwm2
